### PR TITLE
Fixes url escaping issue, and skips invalid urls without erroring

### LINKED ISSUE #376: Url Encoding issue
2018-03-18T16:47:21-04:00 ERROR Unexpected error on record id `6035401/6035401` at file position 45403
    while executing (to_field electronic_access_1display at marc_to_solr/lib/traject_config.rb:246)
    Exception: ArgumentError: invalid URL for 856$u value: www.dietzberlin.de
    /opt/marc_liberation/releases/20180316131332/marc_to_solr/lib/electronic_access_link.rb:40:in `url'

2018-03-18T16:47:21-04:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<ArgumentError: invalid URL for 856$u value: www.dietzberlin.de>
/opt/marc_liberation/releases/20180316131332/marc_to_solr/lib/electronic_access_link.rb:40:in `url': invalid URL for 856$u value: www.dietzberlin.de (ArgumentError)
        from /opt/marc_liberation/releases/20180316131332/marc_to_solr/lib/electronic_access_link.rb:49:in `ark'
        from /opt/marc_liberation/releases/20180316131332/marc_to_solr/lib/princeton_marc.rb:352:in `block in electronic_access_links'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/traject-2.3.1/lib/traject/marc_extractor.rb:244:in `block in collect_matching_lines'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/traject-2.3.1/lib/traject/marc_extractor.rb:229:in `block (2 levels) in each_matching_line'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/traject-2.3.1/lib/traject/marc_extractor.rb:228:in `each'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/traject-2.3.1/lib/traject/marc_extractor.rb:228:in `block in each_matching_line'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/traject-2.3.1/lib/traject/marc_extractor.rb:226:in `each'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/traject-2.3.1/lib/traject/marc_extractor.rb:226:in `each_matching_line'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/traject-2.3.1/lib/traject/marc_extractor.rb:243:in `collect_matching_lines'
        from /opt/marc_liberation/releases/20180316131332/marc_to_solr/lib/princeton_marc.rb:337:in `electronic_access_links'
        from marc_to_solr/lib/traject_config.rb:247:in `block (2 levels) in load_config_file'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/traject-2.3.1/lib/traject/indexer/step.rb:149:in `execute'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/traject-2.3.1/lib/traject/indexer.rb:346:in `block (2 levels) in map_to_context!'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/traject-2.3.1/lib/traject/indexer.rb:400:in `log_mapping_errors'
tor_service.rb:22:in `block in post'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_executor_service.rb:19:in `post'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/traject-2.3.1/lib/traject/thread_pool.rb:108:in `maybe_in_thread_pool'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/traject-2.3.1/lib/traject/indexer.rb:473:in `block in process'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/marc-1.0.2/lib/marc/xml_parsers.rb:37:in `yield_record'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/marc-1.0.2/lib/marc/xml_parsers.rb:72:in `end_element_namespace'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/nokogiri-1.8.2/lib/nokogiri/xml/sax/parser.rb:93:in `parse_with'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/nokogiri-1.8.2/lib/nokogiri/xml/sax/parser.rb:93:in `parse_io'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/nokogiri-1.8.2/lib/nokogiri/xml/sax/parser.rb:81:in `parse'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/marc-1.0.2/lib/marc/xml_parsers.rb:112:in `each'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/traject-2.3.1/lib/traject/marc_reader.rb:86:in `each'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/traject-2.3.1/lib/traject/indexer.rb:443:in `process'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/traject-2.3.1/lib/traject/command_line.rb:67:in `execute'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/gems/traject-2.3.1/bin/traject:14:in `<top (required)>'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/bin/traject:23:in `load'
        from /opt/marc_liberation/shared/bundle/ruby/2.4.0/bin/traject:23:in `<main>'
traject -c marc_to_solr/lib/traject_config.rb /tmp/bib_35.xml -u http://lib-solr2.princeton.edu:8983/solr/catalog-production-backup; true

### LINKED ISSUE #381: Not all characters are escaped in a URL
See https://github.com/pulibrary/marc_liberation/blob/master/marc_to_solr/lib/normal_uri_factory.rb#L21

The URL is only re-escaped if the URL has a space or a % character, but other characters can also cause issues. Line 21 should be removed so the URL is always re-escaped.

### PR DESCRIPTION
**Pull request by tampakis**
Closes #381. Unescapes and escapes all urls except for the ones we generate from arks for the embedded Catalog viewer (urls with #view).
Closes #376. Rather than raising an error from invalid urls we log them.
Updates to latest Voyager Helpers gem.

### CODE REVIEW

**Comment by tampakis** [comment]
@jrgriffiniii, we (@christinach and I) removed the error and error capturing code because it doesn't pass through from the ElectronicLinkFactory to the ElectronicLink class.

File: marc_to_solr/lib/normal_uri_factory.rb [hunk 1]
```diff
@@ -18,7 +18,7 @@ def build
     # Clean the URL value
     # @param value [String] String value for the URL
     def clean(value)
-      return value unless value =~ /[\s%]/
+      return value if value =~ /#view/
       URI.escape(URI.unescape(value).scrub)
```
Comment (jrgriffiniii) [inline marc_to_solr/lib/normal_uri_factory.rb]: This works for me:
```
> cleaned = URI.escape(URI.unescape("http://go.galegroup.com/ps/i.do?id=GALE%257C9781440840869&v=2.1&u=prin77918&it=etoc&p=GVRL&sw=w").scrub)
 => "http://go.galegroup.com/ps/i.do?id=GALE%257C9781440840869&v=2.1&u=prin77918&it=etoc&p=GVRL&sw=w" 
> URI.unescape(cleaned)
 => "http://go.galegroup.com/ps/i.do?id=GALE%7C9781440840869&v=2.1&u=prin77918&it=etoc&p=GVRL&sw=w" 
```
