### PR TITLE
Fixes to CI

### LINKED ISSUE #779: CI never retrieves cached bundle
The initial checksum of the gemlock is correct, but after bundler runs the gemlock does not contain lines for `ruby-oci8` which is excluded from install in ci. This means afterward the bundle cache is saved under a different checksum, so when it looks again on the next run it doesn't find one and does the whole bundle install again.

### PR DESCRIPTION
**Pull request by hackmastera**
Move the admin user configuration from env to yaml
Allow bibliographic_controller#update specs to run/pass in CI (this increases coverage a bit)
Ensure bundle cache is retrieved in ci (this decreases test runs from 12-15 min down to 2 min)

fixes #779

### CODE REVIEW

File: spec/support/with_queue_adapter.rb [hunk 1]
```diff
@@ -0,0 +1,18 @@
+module WithQueueAdapter
```
Comment (carolyncole) [inline spec/support/with_queue_adapter.rb:1]: @hackmastera Is this change needed?  I would have expected the change in environment/test.rb to just do this.

**Review by carolyncole — COMMENTED** [review]
@hackmastera Looks Great.  Just a question.

File: spec/support/with_queue_adapter.rb (hunk 1 above)
Comment (hackmastera) [reply spec/support/with_queue_adapter.rb]: It was a remnant of my roundabout path to this solution. Removed!

**Review by carolyncole — APPROVED** [review]
